import 'normalize.css';
import '../scss/main.scss';
import '../img/logo/rect.svg';
import '../img/logo/VERS.svg';
import '../img/home/box grey.svg';
import '../img/home/box yellow.svg';
import '../img/home/box-green.svg';
import '../img/home/box-purle.svg';
import '../img/home/dctdao.svg';
import '../img/home/ded.svg';
import '../img/home/gate-io.svg';
import '../img/home/pangolin.svg';